/**
 * @description       : 
 * @author            : diego.jacanamijoy@gmail.com
 * @group             : 
 * @last modified on  : 11-26-2020
 * @last modified by  : diego.jacanamijoy@gmail.com
 * Modifications Log 
 * Ver   Date         Author                        Modification
 * 1.0   11-26-2020   diego.jacanamijoy@gmail.com   Initial Version
**/
public with sharing class SM_CompanySettingHandler extends SM_TriggerHandler{

    public SM_CompanySettingHandler(String triggerName){
        super(triggerName);
    }

    /************* Overwrite DML methods *************/

    override public void afterInsert(){
        
    }


    /************* Auxiliar methods *************/

}