/**
 * @description       : 
 * @author            : Jonathan S. Pachon Ariza -> jpachon@legal-credit.com
 * @group             : 
 * @last modified on  : 07-24-2021
 * @last modified by  : Jonathan S. Pachon Ariza -> jpachon.ariza@gmail.com
 * Modifications Log 
 * Ver   Date         Author                                                 Modification
 * 1.0   03-14-2021   Jonathan S. Pachon Ariza -> jpachon@legal-credit.com   Initial Version
**/
@IsTest
public class ZTest_Garbage {

    @IsTest
    static void testGarbage() {
        //SM_LeadHandler.testGarbage();
        // SM_HelperWS.testGarbage();
        /*SM_ConvertLeadLWCController.testGarbage();
        SM_Utils.testGarbage();
        SendContractMannuallyLWCController.testGarbage();
        chargentOrTrController.testGarbage();*/
        // SM_ContractHandler.testGarbage();
        // SM_OpportunityLineItemHandler.testGarbage();
        /*SM_GenerateContractController.testGarbage();
        SM_ChargentPaymentProcessHandler.testGarbage();
        SM_ContractHandler.testGarbage();
        SM_AgreementHandler.testGarbage();
        echosign_dev1__SIGN_Agreement__c obj = new echosign_dev1__SIGN_Agreement__c(Name= 'Test');
        insert obj;
        echosign_dev1__SIGN_Agreement__c  a = [select id from echosign_dev1__SIGN_Agreement__c limit 1];
        update a;*/
        // TransactionLogHandler.testGarbage();
        // ChargentOrders__ChargentOrder__c order = new ChargentOrders__ChargentOrder__c();
        // insert order;
        // ChargentOrders__Transaction__c temp = new ChargentOrders__Transaction__c(ChargentOrders__Order__c = order.Id);
        // insert temp;
    }
}